#server:
#  # 配置服务端口
#  port: 8081
## 指定当前eureka客户端的注册地址，也就是eureka服务的提供方，当前配置的服务的注册服务方
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka,http://${eureka.instance.hostname}:8082/eureka
        #是否需要将自己注册到注册中心(注册中心集群需要设置为true)
    register-with-eureka: false
        #是否需要搜索服务信息 因为自己是注册中心所以为false
    fetch-registry: false
  instance:
    hostname: 127.0.0.1

#指定应用名称
spring:
  application:
    name: eureka-server




